runs:
  using: "composite"
  steps:
    - name: Add GitHub Packages Source and Authentication
      run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.PAT }} --store-password-in-clear-text --name RpmInformatik2 "https://nuget.pkg.github.com/rpm-Informatik2/index.json"
      shell: bash
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
      shell: bash
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
      shell: bash
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
      shell: bash
    - name: Push
      run: dotnet nuget push ${{ github.event.repository.name }}.${VERSION}.nupkg --source https://nuget.pkg.github.com/rpm-Informatik2/index.json --api-key ${GITHUB_TOKEN}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
