on:
  workflow_call:
    secrets:
      PAT:
        required: true

jobs:
  pack-and-push-nuget-package:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      PAT: ${{ secrets.PAT }}
      GITHUB_ACTOR: ${{ github.actor }}
    steps:
      - name: Checkout repository of caller workflow
        uses: actions/checkout@v3
      - name: Set VERSION environment variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Add rpm GitHub Packages Source
        run: dotnet nuget add source --username "$GITHUB_ACTOR" --password "$PAT" --store-password-in-clear-text --name RpmInformatik2 "https://nuget.pkg.github.com/rpm-Informatik2/index.json"
      - name: Build Solution
        run: dotnet build --configuration Release /p:Version="$VERSION"
      - name: Pack NuGet Package
        run: dotnet pack --configuration Release /p:Version="$VERSION" --no-build --output .
      - name: Push to GitHub Packages
        run: dotnet nuget push ${{ github.event.repository.name }}."$VERSION".nupkg --source https://nuget.pkg.github.com/rpm-Informatik2/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
