on:
  workflow_call:
  
jobs:
    build:
      runs-on: windows-latest
      timeout-minutes: 15
      steps:
        - name: Set environment variables
          env:
            PAT: ${{ secrets.PAT }}
            GITHUB_ACTOR: ${{ github.actor }}
        - name: Checkout
          uses: actions/checkout@v2
        - name: Add GitHub Packages Source and Authentication
          run: dotnet nuget add source --username "$env:GITHUB_ACTOR" --password "$env:PAT" --store-password-in-clear-text --name RpmInformatik2 "https://nuget.pkg.github.com/rpm-Informatik2/index.json"
        - name: Build
          run: dotnet build --configuration Release /p:Version=${VERSION}
        - name: Test
          run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
        - name: Pack
          run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
        - name: Push
          run: dotnet nuget push ${{ github.event.repository.name }}.${VERSION}.nupkg --source https://nuget.pkg.github.com/rpm-Informatik2/index.json --api-key ${GITHUB_TOKEN}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
